### ISSUE TITLE
Add support for sessionup v1.4.0

### ISSUE THREAD

**Issue by swithek** [Hyzual/sessionup-sqlitestore#6]
https://github.com/swithek/sessionup/releases/tag/v1.4.0

**Comment by Hyzual** [comment]
:ok_hand:

**Comment by Hyzual** [comment]
Hi @swithek,

I've added support for session metadata in #10. I've mimicked the approach you used for saving metadata in [sessionup-redisstore](https://github.com/swithek/sessionup-redisstore/commit/17be90b542af9e19072afe5c2c21c5d7e4a02739). I've also saved metadata as a string like "key:value;", using `:` as separator between key and value and `;` as separator between "key/value" groups.
Do you think it's a sensible way of storing this metadata for SQL ? I thought of maybe using another table but it adds more complexity and I'm not sure it's worth it. Do you think people will store a lot of things in this field ?

Anyway, thanks for the heads-up about the new version ! :) I'll publish a new minor version when I merge the PR.

**Comment by swithek** [comment]
It's hard to estimate how much data this field may contain but we should do everything to avoid limiting the user. 

I think storing values in a string as you described shouldn't introduce any problems. Also, storing this data in the same row as the whole session makes more sense (after all no other session will be associated with it).

**Comment by Hyzual** [comment]
Indeed. Okay, thank you for the advice! 😊I'll tag the version soon.
